server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.161.205:3306/mybatis-plus?characterEncoding=utf-8&useSSl=false&serverTimezone=GMT%2B8
    username: root
    password: huagen@528
logging:
  level:
    com.mzl.modular: debug
  pattern:
    console: '%p%m%n'
mybatis-plus:
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/modular/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.mzl.modular.entity
  #配置扫描通用枚举
  typeEnumsPackage: com.mzl.core.common.enums
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      logic-delete-field: deleted  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
