server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.161.205:3306/mybatis-plus?characterEncoding=utf-8&useSSl=false&serverTimezone=GMT%2B8
    username: root
    password: huagen@528
logging:
  level:
    com.mzl.modular: debug
  pattern:
    console: '%p%m%n'