server:
  port: 8080
spring:
  datasource:
    dynamic:
      primary: bigger #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        bigger:
          driver-class-name: oracle.jdbc.OracleDriver
          username: BIGGER
          password: BIGGER
          url: jdbc:oracle:thin:@//10.200.7.89:1521/kfpdb
        ba:
          driver-class-name: oracle.jdbc.OracleDriver
          username: BA
          password: BA
          url: jdbc:oracle:thin:@//10.200.7.89:1521/kfpdb
logging:
  level:
    com:
      mzl:
        mapper: debug
